### ISSUE TITLE
merge two `SweetCookieJar`s

### ISSUE THREAD

**Issue by ymelois** [myConsciousness/sweet-cookie-jar#3]
I'm working with https://github.com/jossef/requests which does http requests with seamless cookies in between them. I would like to use this package instead of a custom made `CookieJar`, but `SweetCookieJar` is lacking a way to edit the cookies inside it.

So I would like a way to alter the cookies inside a `SweetCookieJar` (and also a way to merge 2 `SweetCookieJar`s).

This way a CookieJar can be altered with some newly set cookies by the server, and then resent on a new request.

**Comment by myConsciousness** [comment]
Hi @sehnryr , thanks for your feedback!

To be honest, such usage was not envisioned for this library. That said, it is a very interesting use :)

I'm sure there is room for consideration, but do you have a more specific proposal for its use? Do you send the received `SweetCookieJar` object directly to another server again after editing it?

It is not advisable for an object to edit the value of a property contained in itself, as this would be destructive editing. There are several possible solutions, but can't we just get the target cookie with a method such as `find` that this library currently provide, edit it, and return it?

**Comment by ymelois** [comment]
While I make requests with a server, the server can set new cookies in the meantime, and I want to be able to send those on the next request with the previous ones.

For that, I think there could be a + operator on the `SweetCookieJar` to be able to create a new instance which combines the cookies of the two jars, this way it won't be destructive editing.
