### ISSUE TITLE
Can't use with http: 1.0.0 version

### ISSUE THREAD

**Issue by msarkrish** [myConsciousness/sweet-cookie-jar#7]
Hi, 

Thanks for this Sweet Cookie Jar package, I'm trying to use this package with http package version 1.0.0.

But I'm facing the below version solving issue

> Because sweet_cookie_jar 1.1.0 depends on http ^0.13.4 and no versions of sweet_cookie_jar match >1.1.0 <2.0.0, sweet_cookie_jar ^1.1.0 requires http ^0.13.4.
So, because team_appcommon depends on both http ^1.0.0 and sweet_cookie_jar ^1.1.0, version solving failed.

Can you release new version for Sweet Cookie Jar package?

**Comment by myConsciousness** [comment]
Fixed #10
